### ISSUE TITLE
cannot find lgcc

### ISSUE THREAD

**Issue by dvc94ch** [cliffordwolf/icotools#1]
I'm getting the following error when trying to compile the firmware:

```
make firmware.elf
make: which: Command not found
riscv32-unknown-elf-gcc -Os -m32 -march=RV32IXcustom -ffreestanding -nostdlib -Wall -o firmware.elf ../../common/firmware.S ../../common/firmware.c \
        --std=gnu99 -Wl,-Bstatic,-T,../../common/firmware.lds,-Map,firmware.map,--strip-debug -lgcc
/nix/store/3da37l9f2f5jwwv8sgkhyv94qxxf08sb-riscv-toolchain/lib/gcc/riscv32-unknown-elf/5.3.0/../../../../riscv32-unknown-elf/bin/ld: skipping incompatible /nix/store/3da37l9f2f5jwwv8sgkhyv94qxxf08sb-riscv-toolchain/lib/gcc/riscv32-unknown-elf/5.3.0/libgcc.a when searching for -lgcc
/nix/store/3da37l9f2f5jwwv8sgkhyv94qxxf08sb-riscv-toolchain/lib/gcc/riscv32-unknown-elf/5.3.0/../../../../riscv32-unknown-elf/bin/ld: cannot find -lgcc
collect2: error: ld returned 1 exit status
icosoc.mk:86: recipe for target 'firmware.elf' failed
make: *** [firmware.elf] Error 1
```

when inspecting the skipped libgcc it looks ok to me:

```
file /tmp/libgcc/*.o
_absvdi2.o:             ELF 32-bit LSB relocatable, UCB RISC-V, version 1 (SYSV), not stripped
```

I built the toolchain from commit 06c957a like recommended in the README. Any ideas what the problem might be?

**Comment by cliffordwolf** [comment]
hmm.. when you run `riscv32-unknown-elf-readelf -h` on the .o file from libgcc, and on the .o files generated by the compiler, you will probably discover that one has `Flags: soft-float ABI` set and the other one does not.

06c957a is an older version of the compiler. Unfortunately I never updated the version referenced in that README file. I've now replaced the build instructions with a link to the primary source (the PicoRV32 README).

Can you try again with current git head of IcoSoC and PicoRV32? The current "golden" riscv-gnu-toolchain commit is 34db4e0.

**Comment by dvc94ch** [comment]
I updated the toolchain, but the problem persists. I suspect it has something to do with the distro that I'm using.
The flags did change to soft float after the update, but I couldn't find a mismatch before or after.

**Comment by cliffordwolf** [comment]
> I updated the toolchain, but the problem persists. I suspect it has something to do with the distro that I'm using [..]

Then I'll close the issue for now. Just post a comment if there is anything else I can do, and I will re-open it. If you manage to solve the problem, and think there is something I should mention in the documentation to help others avoid the same issue, please also leave a comment with the relevant information.

**Comment by dvc94ch** [comment]
Found the problem. Nix was stripping debugging symbols and somehow messing libgcc up. Thank you for your suggestions.
